project:
  type: website
  output-dir: .

website:
  title: "paneltime.github.io"
  sidebar:
    style: floating
    contents:
      - index.md           # appears first
      - attributes.md           # appears second
      - options.md 
      - hfunc.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    math: mathjax
